# Generated by Django 3.0.6 on 2020-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='orbits',
            fields=[
                ('ORDINAL', models.TextField()),
                ('COMMENT', models.TextField()),
                ('ORIGINATOR', models.TextField()),
                ('NORAD_CAT_ID', models.TextField()),
                ('OBJECT_NAME', models.TextField()),
                ('OBJECT_TYPE', models.TextField()),
                ('CLASSIFICATION_TYPE', models.TextField()),
                ('INTLDES', models.TextField()),
                ('EPOCH', models.TextField()),
                ('EPOCH_MICROSECONDS', models.TextField()),
                ('MEAN_MOTION', models.TextField()),
                ('ECCENTRICITY', models.TextField()),
                ('INCLINATION', models.TextField()),
                ('RA_OF_ASC_NODE', models.TextField()),
                ('ARG_OF_PERICENTER', models.TextField()),
                ('MEAN_ANOMALY', models.TextField()),
                ('EPHEMERIS_TYPE', models.TextField()),
                ('ELEMENT_SET_NO', models.TextField()),
                ('REV_AT_EPOCH', models.TextField()),
                ('BSTAR', models.TextField()),
                ('MEAN_MOTION_DOT', models.TextField()),
                ('MEAN_MOTION_DDOT', models.TextField()),
                ('FILE', models.TextField()),
                ('TLE_LINE0', models.TextField()),
                ('TLE_LINE1', models.TextField()),
                ('TLE_LINE2', models.TextField()),
                ('OBJECT_ID', models.TextField()),
                ('OBJECT_NUMBER', models.TextField()),
                ('SEMIMAJOR_AXIS', models.TextField()),
                ('PERIOD', models.TextField()),
                ('APOGEE', models.TextField()),
                ('PERIGEE', models.TextField()),
                ('DECAYED', models.TextField()),
            ] 
        )    
    ]     


    